---
  instance_name:
    description: "Instance name, provided by ServiceNow"
    type: "string"
    secret: false
    required: true
  username:
    description: "Username for the servicenow account"
    type: "string"
    required: true
  password:
    description: "Password for the servicenow account"
    type: "string"
    secret: true
    required: true
  custom_params:
    description: "ServiceNow options that will be passed to all requests"
    type: object
    required: false

  sensors:
    type: object
    properties:
      taskinfo:
        type: object
        properties:
          assignment_group:
            descritpion: "Assignment Group in ServiceNow to monitor."
            type: string
            default: "6697f807db3c1b441d893a92ba961992"
          state:
            description: "What state REQs needs to be monitored."
            type: integer
            default: 0
          short_description:
            description: "Specific task to monitor"
            type: string
          table:
            description: "ServiceNOW Table to monitor."
            type: string
            default: "sc_task"
        